'use strict';

// GENERATED by scripts/sync-hosts-data.js — do not edit by hand.
//
// The hosts block this app writes with elevated rights, pinned to one upstream
// commit and shipped with the release. It is not downloaded at run time: that
// download came from a moving branch with no integrity check, and it is the
// only privileged write the app performs (#54).
//
// Update deliberately, with a diff to review:
//   npm run sync:hosts -- <commit>

const HOSTS_SOURCE_REPO = "Flowseal/zapret-discord-youtube";
const HOSTS_SOURCE_PATH = ".service/hosts";
const HOSTS_SOURCE_COMMIT = "5de5901e2173da137651fc9530cea094c9b0d6c9";
const HOSTS_SOURCE_URL =
  `https://raw.githubusercontent.com/${HOSTS_SOURCE_REPO}/${HOSTS_SOURCE_COMMIT}/${HOSTS_SOURCE_PATH}`;

// SHA-256 of HOSTS_DATA exactly as written below, so the checked-in copy can be
// proved to be the pinned upstream bytes.
const HOSTS_DATA_SHA256 = "242faedf803458ec5c41bd485d9f580211757a27ce56b88283d302b6408e9355";

const HOSTS_DATA = [
  "185.199.109.133 objects.githubusercontent.com",
  "185.199.109.133 raw.githubusercontent.com",
  "185.199.109.133 release-assets.githubusercontent.com",
  "185.199.108.133 private-user-images.githubusercontent.com",
  "185.199.108.133 gist.githubusercontent.com",
  "185.199.108.133 avatars.githubusercontent.com",
  "",
  "149.154.167.220 my.telegram.org",
  "149.154.167.220 desktop.telegram.org",
  "149.154.167.220 macos.telegram.org",
  "149.154.167.220 oauth.telegram.org",
  "149.154.167.220 oauth.tg.dev",
  "149.154.167.220 cdn.telesco.pe",
  "149.154.167.220 cdn1.telesco.pe",
  "149.154.167.220 cdn2.telesco.pe",
  "149.154.167.220 cdn3.telesco.pe",
  "149.154.167.220 cdn4.telesco.pe",
  "149.154.167.220 cdn5.telesco.pe",
  "149.154.167.220 cdn6.telesco.pe",
  "149.154.167.220 core.telegram.org",
  "149.154.167.220 zws4.web.telegram.org",
  "149.154.167.220 vesta.web.telegram.org",
  "149.154.167.220 vesta-1.web.telegram.org",
  "149.154.167.220 venus-1.web.telegram.org",
  "149.154.167.220 telegram.me",
  "149.154.167.220 telegram.dog",
  "149.154.167.220 telegram.space",
  "149.154.167.220 telesco.pe",
  "149.154.167.220 tg.dev",
  "149.154.167.220 telegram.org",
  "149.154.167.220 t.me",
  "149.154.167.220 api.telegram.org",
  "149.154.167.220 td.telegram.org",
  "149.154.167.220 venus.web.telegram.org",
  "149.154.167.220 web.telegram.org",
  "149.154.167.220 kws2-1.web.telegram.org",
  "149.154.167.220 kws2.web.telegram.org",
  "149.154.167.220 kws4-1.web.telegram.org",
  "149.154.167.220 kws4.web.telegram.org",
  "149.154.167.220 zws2-1.web.telegram.org",
  "149.154.167.220 zws2.web.telegram.org",
  "149.154.167.220 zws4-1.web.telegram.org",
  "",
  "162.159.138.232 discord.com",
  "162.159.137.232 discord.com",
  "162.159.128.233 discord.com",
  "162.159.135.232 discord.com",
  "162.159.138.232 updates.discord.com",
  "162.159.137.232 updates.discord.com",
  "162.159.128.233 updates.discord.com",
  "162.159.135.232 updates.discord.com"
].join('\n');

module.exports = {
  HOSTS_DATA,
  HOSTS_DATA_SHA256,
  HOSTS_SOURCE_COMMIT,
  HOSTS_SOURCE_PATH,
  HOSTS_SOURCE_REPO,
  HOSTS_SOURCE_URL
};
